version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - $PWD:/home/gobarber/api
    working_dir: /home/gobarber/api
    depends_on:
      - pg
    networks:
      - go_barber_network
  pg:
    image: postgres:12.5-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gostack_gobarber
    networks:
      - go_barber_network
networks:
  go_barber_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
